version: "3.9"
services:
  proxy:
    container_name: hello-app-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hello-app-net

  api:
    container_name: hello-app-api
    image: longthanhle1122/hello-app-api:latest
    networks:
      - hello-app-net

  fe:
    container_name: hello-app-fe
    image: longthanhle1122/hello-app-fe:latest
    networks:
      - hello-app-net

networks:
  hello-app-net:
    name: hello-app-net
